import '../models/models.dart';

class MockData {
  static final AdminUser currentAdmin = AdminUser(
    id: 'admin_001',
    name: 'Arjun Menon',
    email: 'arjun@flexit.io',
    role: 'Super Admin',
  );

  static final DashboardStats stats = DashboardStats(
    totalUsers: 2847,
    activeUsers: 2341,
    newUsersThisMonth: 143,
    userGrowthPercent: 12.4,
    liveDevices: 4219,
    totalDevices: 5103,
    offlineDevices: 884,
    deviceGrowthPercent: 8.7,
    totalRevenue: 847293.50,
    revenueThisMonth: 74820.00,
    revenueGrowthPercent: 18.2,
    totalErrors: 347,
    openErrors: 42,
    criticalErrors: 7,
    errorChangePercent: -5.3,
  );

  static final List<DeviceInfo> sampleDevices = [
    DeviceInfo(
      deviceId: 'DEV-001-AX9',
      deviceName: 'POS Terminal Alpha',
      macAddress: 'A4:C3:F0:85:AC:B1',
      androidVersion: '13',
      osName: 'Android',
      model: 'Sunmi T2 Mini',
      manufacturer: 'Sunmi',
      isOnline: true,
      isActive: true,
      ownerId: 'USR-0042',
      ownerName: 'Nisha Patel',
      businessName: 'Patel Retail Hub',
      registeredAt: DateTime(2023, 6, 15),
      lastSeen: DateTime.now().subtract(const Duration(minutes: 3)),
      appVersion: '2.4.1',
      ipAddress: '192.168.1.105',
      location: 'Mumbai, MH',
      storageUsedGB: 4.2,
      storageTotalGB: 16.0,
      batteryLevel: 87,
      firmwareVersion: 'FW-2.1.0',
      serialNumber: 'SN20230615001',
    ),
    DeviceInfo(
      deviceId: 'DEV-002-BK3',
      deviceName: 'Kitchen Display Unit',
      macAddress: 'B8:D0:4A:C2:11:9E',
      androidVersion: '12',
      osName: 'Android',
      model: 'Sunmi D3 Pro',
      manufacturer: 'Sunmi',
      isOnline: true,
      isActive: true,
      ownerId: 'USR-0089',
      ownerName: 'Rahul Sharma',
      businessName: 'Sharma Foods',
      registeredAt: DateTime(2023, 8, 22),
      lastSeen: DateTime.now().subtract(const Duration(minutes: 1)),
      appVersion: '2.4.1',
      ipAddress: '10.0.0.55',
      location: 'Delhi, DL',
      storageUsedGB: 6.7,
      storageTotalGB: 32.0,
      batteryLevel: 100,
      firmwareVersion: 'FW-2.0.5',
      serialNumber: 'SN20230822003',
    ),
    DeviceInfo(
      deviceId: 'DEV-003-CX7',
      deviceName: 'Counter Terminal 3',
      macAddress: 'DC:A6:32:1B:7F:22',
      androidVersion: '11',
      osName: 'Android',
      model: 'Urovo DT50',
      manufacturer: 'Urovo',
      isOnline: false,
      isActive: true,
      ownerId: 'USR-0115',
      ownerName: 'Priya Iyer',
      businessName: 'Iyer Textiles',
      registeredAt: DateTime(2022, 11, 10),
      lastSeen: DateTime.now().subtract(const Duration(hours: 14)),
      appVersion: '2.3.8',
      ipAddress: '172.16.0.33',
      location: 'Chennai, TN',
      storageUsedGB: 9.1,
      storageTotalGB: 16.0,
      batteryLevel: 23,
      firmwareVersion: 'FW-1.9.2',
      serialNumber: 'SN20221110007',
    ),
    DeviceInfo(
      deviceId: 'DEV-004-DZ2',
      deviceName: 'Billing Station Main',
      macAddress: 'F0:18:98:64:2A:B5',
      androidVersion: '13',
      osName: 'Android',
      model: 'Sunmi V2 Pro',
      manufacturer: 'Sunmi',
      isOnline: true,
      isActive: true,
      ownerId: 'USR-0201',
      ownerName: 'Kiran Reddy',
      businessName: 'Reddy Supermart',
      registeredAt: DateTime(2024, 1, 5),
      lastSeen: DateTime.now().subtract(const Duration(seconds: 45)),
      appVersion: '2.4.1',
      ipAddress: '192.168.10.20',
      location: 'Hyderabad, TS',
      storageUsedGB: 2.8,
      storageTotalGB: 32.0,
      batteryLevel: 64,
      firmwareVersion: 'FW-2.1.0',
      serialNumber: 'SN20240105012',
    ),
    DeviceInfo(
      deviceId: 'DEV-005-EF8',
      deviceName: 'Self-Checkout Kiosk',
      macAddress: '3C:22:FB:88:47:D0',
      androidVersion: '12',
      osName: 'Android',
      model: 'PAX A920 Pro',
      manufacturer: 'PAX',
      isOnline: true,
      isActive: false,
      ownerId: 'USR-0042',
      ownerName: 'Nisha Patel',
      businessName: 'Patel Retail Hub',
      registeredAt: DateTime(2023, 4, 18),
      lastSeen: DateTime.now().subtract(const Duration(minutes: 22)),
      appVersion: '2.4.0',
      ipAddress: '192.168.1.108',
      location: 'Mumbai, MH',
      storageUsedGB: 11.3,
      storageTotalGB: 64.0,
      batteryLevel: 92,
      firmwareVersion: 'FW-2.0.8',
      serialNumber: 'SN20230418005',
    ),
  ];

  static final List<Customer> customers = [
    Customer(
      id: 'USR-0042',
      name: 'Nisha Patel',
      email: 'nisha.patel@patelretail.in',
      phone: '+91 98201 45678',
      address: '12, Linking Road, Bandra West',
      city: 'Mumbai',
      country: 'India',
      plan: 'Enterprise',
      status: 'active',
      isOnline: true,
      deviceCount: 2,
      totalUsageGB: 284.5,
      monthlyUsageGB: 31.2,
      joinDate: DateTime(2022, 3, 14),
      nextPaymentDate: DateTime.now().add(const Duration(days: 8)),
      monthlyCharge: 4999.00,
      errorCount: 3,
      businessName: 'Patel Retail Hub',
      avatarInitials: 'NP',
      paymentHistory: [
        PaymentRecord(
          transactionId: 'TXN-20240501-001',
          date: DateTime(2024, 5, 1),
          amount: 4999.00,
          currency: 'INR',
          status: 'success',
          method: 'card',
          customerId: 'USR-0042',
          customerName: 'Nisha Patel',
          businessName: 'Patel Retail Hub',
          plan: 'Enterprise',
          description: 'Monthly subscription - Enterprise Plan',
          cardLast4: '4242',
          invoiceId: 'INV-2024-0501',
        ),
        PaymentRecord(
          transactionId: 'TXN-20240401-001',
          date: DateTime(2024, 4, 1),
          amount: 4999.00,
          currency: 'INR',
          status: 'success',
          method: 'card',
          customerId: 'USR-0042',
          customerName: 'Nisha Patel',
          businessName: 'Patel Retail Hub',
          plan: 'Enterprise',
          description: 'Monthly subscription - Enterprise Plan',
          cardLast4: '4242',
          invoiceId: 'INV-2024-0401',
        ),
      ],
      devices: [sampleDevices[0], sampleDevices[4]],
    ),
    Customer(
      id: 'USR-0089',
      name: 'Rahul Sharma',
      email: 'rahul@sharmafoods.com',
      phone: '+91 99110 23456',
      address: '45, Lajpat Nagar II',
      city: 'Delhi',
      country: 'India',
      plan: 'Professional',
      status: 'active',
      isOnline: true,
      deviceCount: 1,
      totalUsageGB: 128.9,
      monthlyUsageGB: 18.7,
      joinDate: DateTime(2023, 1, 8),
      nextPaymentDate: DateTime.now().add(const Duration(days: 22)),
      monthlyCharge: 2499.00,
      errorCount: 1,
      businessName: 'Sharma Foods',
      avatarInitials: 'RS',
      paymentHistory: [
        PaymentRecord(
          transactionId: 'TXN-20240510-003',
          date: DateTime(2024, 5, 10),
          amount: 2499.00,
          currency: 'INR',
          status: 'success',
          method: 'upi',
          customerId: 'USR-0089',
          customerName: 'Rahul Sharma',
          businessName: 'Sharma Foods',
          plan: 'Professional',
          description: 'Monthly subscription - Professional Plan',
          invoiceId: 'INV-2024-0510',
        ),
      ],
      devices: [sampleDevices[1]],
    ),
    Customer(
      id: 'USR-0115',
      name: 'Priya Iyer',
      email: 'priya.iyer@iyertextiles.com',
      phone: '+91 94440 78901',
      address: '78, T. Nagar Main Road',
      city: 'Chennai',
      country: 'India',
      plan: 'Starter',
      status: 'flagged',
      isOnline: false,
      deviceCount: 1,
      totalUsageGB: 47.3,
      monthlyUsageGB: 6.4,
      joinDate: DateTime(2022, 9, 20),
      nextPaymentDate: DateTime.now().subtract(const Duration(days: 3)),
      monthlyCharge: 999.00,
      errorCount: 8,
      businessName: 'Iyer Textiles',
      avatarInitials: 'PI',
      paymentHistory: [
        PaymentRecord(
          transactionId: 'TXN-20240415-009',
          date: DateTime(2024, 4, 15),
          amount: 999.00,
          currency: 'INR',
          status: 'failed',
          method: 'bank',
          customerId: 'USR-0115',
          customerName: 'Priya Iyer',
          businessName: 'Iyer Textiles',
          plan: 'Starter',
          description: 'Monthly subscription - Starter Plan',
          bankName: 'Canara Bank',
          invoiceId: 'INV-2024-0415',
        ),
      ],
      devices: [sampleDevices[2]],
    ),
    Customer(
      id: 'USR-0201',
      name: 'Kiran Reddy',
      email: 'kiran@reddysupermart.in',
      phone: '+91 87000 34567',
      address: '22, Jubilee Hills, Road No. 36',
      city: 'Hyderabad',
      country: 'India',
      plan: 'Enterprise',
      status: 'active',
      isOnline: true,
      deviceCount: 1,
      totalUsageGB: 192.1,
      monthlyUsageGB: 24.8,
      joinDate: DateTime(2024, 1, 5),
      nextPaymentDate: DateTime.now().add(const Duration(days: 15)),
      monthlyCharge: 4999.00,
      errorCount: 0,
      businessName: 'Reddy Supermart',
      avatarInitials: 'KR',
      paymentHistory: [
        PaymentRecord(
          transactionId: 'TXN-20240505-005',
          date: DateTime(2024, 5, 5),
          amount: 4999.00,
          currency: 'INR',
          status: 'success',
          method: 'card',
          customerId: 'USR-0201',
          customerName: 'Kiran Reddy',
          businessName: 'Reddy Supermart',
          plan: 'Enterprise',
          description: 'Monthly subscription - Enterprise Plan',
          cardLast4: '8888',
          invoiceId: 'INV-2024-0505',
        ),
      ],
      devices: [sampleDevices[3]],
    ),
    Customer(
      id: 'USR-0287',
      name: 'Anjali Singh',
      email: 'anjali.singh@fashionkart.co',
      phone: '+91 70002 56789',
      address: '5B, MG Road, Indiranagar',
      city: 'Bengaluru',
      country: 'India',
      plan: 'Professional',
      status: 'banned',
      isOnline: false,
      deviceCount: 0,
      totalUsageGB: 12.0,
      monthlyUsageGB: 0,
      joinDate: DateTime(2023, 7, 1),
      nextPaymentDate: DateTime.now().subtract(const Duration(days: 30)),
      monthlyCharge: 2499.00,
      errorCount: 22,
      businessName: 'FashionKart',
      avatarInitials: 'AS',
      paymentHistory: [],
      devices: [],
    ),
  ];

  static final List<PaymentRecord> allPayments = [
    PaymentRecord(
      transactionId: 'TXN-20240515-011',
      date: DateTime(2024, 5, 15, 14, 32),
      amount: 4999.00,
      currency: 'INR',
      status: 'success',
      method: 'card',
      customerId: 'USR-0042',
      customerName: 'Nisha Patel',
      businessName: 'Patel Retail Hub',
      plan: 'Enterprise',
      description: 'Monthly subscription - Enterprise Plan',
      cardLast4: '4242',
      invoiceId: 'INV-2024-0515-011',
    ),
    PaymentRecord(
      transactionId: 'TXN-20240514-009',
      date: DateTime(2024, 5, 14, 10, 15),
      amount: 2499.00,
      currency: 'INR',
      status: 'success',
      method: 'upi',
      customerId: 'USR-0089',
      customerName: 'Rahul Sharma',
      businessName: 'Sharma Foods',
      plan: 'Professional',
      description: 'Monthly subscription - Professional Plan',
      invoiceId: 'INV-2024-0514-009',
    ),
    PaymentRecord(
      transactionId: 'TXN-20240513-008',
      date: DateTime(2024, 5, 13, 16, 48),
      amount: 4999.00,
      currency: 'INR',
      status: 'success',
      method: 'card',
      customerId: 'USR-0201',
      customerName: 'Kiran Reddy',
      businessName: 'Reddy Supermart',
      plan: 'Enterprise',
      description: 'Monthly subscription - Enterprise Plan',
      cardLast4: '8888',
      invoiceId: 'INV-2024-0513-008',
    ),
    PaymentRecord(
      transactionId: 'TXN-20240512-007',
      date: DateTime(2024, 5, 12, 9, 22),
      amount: 999.00,
      currency: 'INR',
      status: 'failed',
      method: 'bank',
      customerId: 'USR-0115',
      customerName: 'Priya Iyer',
      businessName: 'Iyer Textiles',
      plan: 'Starter',
      description: 'Monthly subscription - Starter Plan',
      bankName: 'Canara Bank',
      invoiceId: 'INV-2024-0512-007',
    ),
    PaymentRecord(
      transactionId: 'TXN-20240511-006',
      date: DateTime(2024, 5, 11, 11, 5),
      amount: 2499.00,
      currency: 'INR',
      status: 'refunded',
      method: 'card',
      customerId: 'USR-0287',
      customerName: 'Anjali Singh',
      businessName: 'FashionKart',
      plan: 'Professional',
      description: 'Refund - Policy violation',
      cardLast4: '1234',
      invoiceId: 'INV-2024-0511-006',
    ),
    PaymentRecord(
      transactionId: 'TXN-20240510-005',
      date: DateTime(2024, 5, 10, 8, 33),
      amount: 999.00,
      currency: 'INR',
      status: 'pending',
      method: 'upi',
      customerId: 'USR-0331',
      customerName: 'Vikram Nair',
      businessName: 'Nair Electronics',
      plan: 'Starter',
      description: 'Monthly subscription - Starter Plan',
      invoiceId: 'INV-2024-0510-005',
    ),
  ];

  static final List<ErrorRecord> allErrors = [
    ErrorRecord(
      errorId: 'ERR-20240515-0142',
      timestamp: DateTime(2024, 5, 15, 15, 42, 18),
      errorCode: 'PAYMENT_GATEWAY_TIMEOUT',
      errorType: 'payment',
      severity: 'critical',
      message:
          'Payment gateway connection timed out after 30s. Transaction not completed.',
      stackTrace:
          'PaymentService.processPayment(PaymentService.dart:142)\nCheckoutViewModel.submitOrder(CheckoutViewModel.dart:88)\n...',
      deviceId: 'DEV-001-AX9',
      deviceName: 'POS Terminal Alpha',
      ownerId: 'USR-0042',
      ownerName: 'Nisha Patel',
      businessName: 'Patel Retail Hub',
      appVersion: '2.4.1',
      osVersion: 'Android 13',
      status: 'open',
    ),
    ErrorRecord(
      errorId: 'ERR-20240515-0138',
      timestamp: DateTime(2024, 5, 15, 14, 28, 55),
      errorCode: 'SYNC_FAILED_NETWORK',
      errorType: 'network',
      severity: 'high',
      message:
          'Data sync failed — no internet connection detected for >10 minutes.',
      stackTrace:
          'SyncManager.syncData(SyncManager.dart:67)\nBackgroundService.run(BackgroundService.dart:33)\n...',
      deviceId: 'DEV-003-CX7',
      deviceName: 'Counter Terminal 3',
      ownerId: 'USR-0115',
      ownerName: 'Priya Iyer',
      businessName: 'Iyer Textiles',
      appVersion: '2.3.8',
      osVersion: 'Android 11',
      status: 'investigating',
    ),
    ErrorRecord(
      errorId: 'ERR-20240514-0291',
      timestamp: DateTime(2024, 5, 14, 20, 11, 3),
      errorCode: 'APP_CRASH_NULL_POINTER',
      errorType: 'crash',
      severity: 'critical',
      message:
          'Null pointer exception in product catalog loader. App forced close.',
      stackTrace:
          'CatalogRepository.loadProducts(CatalogRepository.dart:209)\nHomeScreen.build(HomeScreen.dart:44)\n...',
      deviceId: 'DEV-002-BK3',
      deviceName: 'Kitchen Display Unit',
      ownerId: 'USR-0089',
      ownerName: 'Rahul Sharma',
      businessName: 'Sharma Foods',
      appVersion: '2.4.1',
      osVersion: 'Android 12',
      status: 'resolved',
      resolvedAt: '2024-05-14 22:30',
      resolvedBy: 'Arjun Menon',
    ),
    ErrorRecord(
      errorId: 'ERR-20240514-0183',
      timestamp: DateTime(2024, 5, 14, 11, 45, 30),
      errorCode: 'AUTH_TOKEN_EXPIRED',
      errorType: 'auth',
      severity: 'medium',
      message:
          'JWT auth token expired and silent refresh failed. User logged out unexpectedly.',
      stackTrace:
          'AuthService.refreshToken(AuthService.dart:88)\nApiClient.sendRequest(ApiClient.dart:155)\n...',
      deviceId: 'DEV-004-DZ2',
      deviceName: 'Billing Station Main',
      ownerId: 'USR-0201',
      ownerName: 'Kiran Reddy',
      businessName: 'Reddy Supermart',
      appVersion: '2.4.1',
      osVersion: 'Android 13',
      status: 'resolved',
      resolvedAt: '2024-05-14 13:00',
      resolvedBy: 'Arjun Menon',
    ),
    ErrorRecord(
      errorId: 'ERR-20240513-0077',
      timestamp: DateTime(2024, 5, 13, 9, 2, 14),
      errorCode: 'PRINTER_CONN_FAILED',
      errorType: 'hardware',
      severity: 'low',
      message:
          'Bluetooth printer connection failed. Receipt printing unavailable.',
      stackTrace:
          'PrinterService.connect(PrinterService.dart:32)\nOrderComplete.printReceipt(OrderComplete.dart:77)\n...',
      deviceId: 'DEV-005-EF8',
      deviceName: 'Self-Checkout Kiosk',
      ownerId: 'USR-0042',
      ownerName: 'Nisha Patel',
      businessName: 'Patel Retail Hub',
      appVersion: '2.4.0',
      osVersion: 'Android 12',
      status: 'ignored',
    ),
  ];
}
